spring:
  profiles:
    default: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/flickit
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: xLaG2/dGZ9B1cHZGU8I+GHZlGhkBPLf88uAYbwMLYJY=
  expiration-ms: 86400000  # 24 hours in milliseconds

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db:5432/flickit
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: xLaG2/dGZ9B1cHZGU8I+GHZlGhkBPLf88uAYbwMLYJY=
  expiration-ms: 86400000  # 24 hours in milliseconds

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/flickit
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: xLaG2/dGZ9B1cHZGU8I+GHZlGhkBPLf88uAYbwMLYJY=
  expiration-ms: 86400000  # 24 hours in milliseconds

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show-sql: true
  h2:
    console:
      enabled: true

# JWT Configuration
jwt:
  secret: xLaG2/dGZ9B1cHZGU8I+GHZlGhkBPLf88uAYbwMLYJY=
  expiration-ms: 86400000  # 24 hours in milliseconds